- name: Listen for Machine resource events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1 
        kind: Event
        namespace: openshift-machine-api
        user: "{{ k8s_user }}"
        password: "{{ k8s_pass }}"
        host: "{{ k8s_host }}"
  rules:
    - name: Notify Deleted machines
      condition: event.resource.reason == "Deleted" and event.resource.count == 1
      action:
        run_job_template:
          name: "Update machine in SNOW"
          organization: "Default"
          job_args:
            extra_vars:
              machine: "{{ event.resource.involvedObject.name }}"
              action: "delete"
    - name: Notify Added machines
      condition: event.resource.reason == "Updated" and event.resource.count == 1
      action:
        run_job_template:
          name: "Update machine in SNOW"
          organization: "Default"
          job_args:
            extra_vars:
              machine: "{{ event.resource.involvedObject.name }}" 
              action: "add" 
