- name: Listen for Machine resource events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: machine.openshift.io/v1beta1
        kind: Machine
        namespace: openshift-machine-api
  rules:
    - name: Notify DELETE
      condition: event.type == "DELETED"
      action:
        debug:
          #msg: "Machine deleted: {{ event.resource.metadata.name }}"
          var: event.resource
    - name: Notify ADD
      condition: event.type != "DELETED" and event.resource.status.providerStatus.vmState == "Running"
      action:
        debug:
          #msg: "Machine created: {{ event.resource.metadata.name }} - Status: {{ event.resource.status.providerStatus.conditions[0].type }} - Reason: {{ event.resource.status.providerStatus.conditions[0].reason }}  - Reason: {{ event.resource.status.providerStatus.vmState }}"
          var: event.resource
