- name: Listen for Machine resource events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1 
        kind: Event
        namespace: openshift-machine-api
  rules:
    - name: Notify added machines
      condition: event.resource.type == "Updated"
      action:
        debug:
          msg:  "Machine Added: {{ event.resource.involvedObject.name }}"
    - name: Notify deleted machies
      condition: event.resource.type == "Deleted"
      action:
        debug:
          msg:  "Machine Deleted: {{ event.resource.involvedObject.name }}"
