- name: Listen for Machine resource events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1 
        kind: Event
        namespace: openshift-machine-api
  rules:
    - name: Notify deleted machines
      condition:
        all:
          - event.type == "ADDED"
          - event.message is match("Deleted machine.*", ignorecase=true) 
      action:
        debug:
          var: event
    - name: Notify added machies
      condition:
        all:
          - event.type == "ADDED"
          - event.message is match("Updated machine.*", ignorecase=true) 
      action:
        debug:
          var: event
