- name: Listen for newly created Machines and add the new host to SNOW
  hosts: localhost
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        namespace: default
  rules:
    - name: Execute Playbook
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: "Add host to SNOW"
          organization: "Default"  
