- name: Listen for Machine resource events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1 
        kind: Event
        namespace: openshift-machine-api
  rules:
    - name: Notify deleted machines
      condition: event.resource.reason == "Deleted"
      action:
        debug:
          msg:  "Machine deleted: {{ event.resource.involvedObject.name }}"
    - name: Notify added machines
      condition: event.resource.reason == "Updated"
      action:
        debug:
          msg:  "Machine added: {{ event.resource.involvedObject.name }}"
